general:
  project: Uninuvola
  domain: uninuvola.unipg.it

vault:
  ip: 10.9.245.2
  port: 8200
  protocol: http
  oidcs:
    web:
      appname: web
      scopename: web
      providername: web
      redirect_uris: https://www.uninuvola.unipg.it/auth
      secretfile: web.env
    jupyter:
      appname: jupyter
      scopename: jupyter
      providername: jupyter
      redirect_uris: https://compute.uninuvola.unipg.it/jup
      secretfile: jupyter.env

openldap:
  ip: 10.9.245.1
  port: 389
  ougroups: groups
  ouusers: users
  user: admin
  readonlyuser: readonly

ldapadmin:
  ip: 10.9.245.3

redis:
  ip: 10.9.245.4
  port: 6379
  username: default

ldapsync:
  ip: 10.9.245.5

web:
  ip: 10.9.245.6

ldapproxy:
  ip: 10.9.245.7
  port: 1111
  endpoint: 1111
