general:
  project: Uninuvola
  domain: uninuvola.unipg.it

vault:
  ip: 10.9.245.2
  public_url: https://vault.uninuvola.unipg.it:8200
  port: 8200
  protocol: http
  oidcs:
    web:
      appname: web
      scopes: 
        - { "name": "web", "template": "{{ \"metadata\": {{{{identity.entity.aliases.{_accessor}.metadata}}}} }}" }
      providername: web
      redirect_uris: https://www.uninuvola.unipg.it/auth
      secretfile: web.env
    jupyter:
      appname: jupyter
      scopes: 
        - { "name": "user", "template": "{{ \"username\": {{{{identity.entity.aliases.{_accessor}.metadata.name}}}} }}" }
        - { "name": "groups", "template": "{{ \"groups\": {{{{identity.entity.groups.names }}}} }}" }
      providername: jupyter
      redirect_uris: https://compute.uninuvola.unipg.it/hub/oauth_callback
      secretfile: jupyter.env

openldap:
  ip: 10.9.245.1
  port: 389
  groups:
    - admin
    - users
  ougroups: groups
  ouusers: users
  user: admin
  readonlyuser: readonly

ldapadmin:
  ip: 10.9.245.3

redis:
  ip: 10.9.245.4
  port: 6379
  username: default
  database: 0

ldapsync:
  ip: 10.9.245.5
  source_uri: ldap://141.250.2.135
  source_basedn: dc=unipg,dc=it

web:
  ip: 10.9.245.6
  public_url: https://www.uninuvola.unipg.it
  dns_ip: 8.8.8.8

ldapproxy:
  ip: 10.9.245.7
  port: 1111
  endpoint: 1111
