[tool.poetry]
name = "uninuvola-init"
version = "0.1.0"
description = "Kickstarter script for all uninuvola's software"
authors = ["Nicolò Vescera <nicolo.vescera@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
hvac = "^2.3.0"

[tool.poetry.scripts]
uninuvola-init = "uninuvola_init.cli:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
